{% set name = "types-maxminddb" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-maxminddb-{{ version }}.tar.gz
  sha256: 9146df7098d834d5f584d2393af85ef9294c67a16ace991f1635a2aa331f7854

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-ipaddress

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/maxminddb-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for maxminddb
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
