{% set name = "types-maxminddb" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-maxminddb-{{ version }}.tar.gz
  sha256: 839f8db86205ad13a8de0a2ca4a69bf1ffa18828324f305c09798224b880532f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-ipaddress

test:
  commands:
    - test -f $SP_DIR/maxminddb-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for maxminddb
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
