{% set version = "1.5.0" %}

package:
  name: types-maxminddb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-maxminddb/types-maxminddb-{{ version }}.tar.gz
  sha256: 9146df7098d834d5f584d2393af85ef9294c67a16ace991f1635a2aa331f7854

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-ipaddress

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/maxminddb-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for maxminddb
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
